# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

UpdateNumMat <- function(raw_mat, new_mat, row_idx, col_idx) {
    .Call('_bbknnR_UpdateNumMat', PACKAGE = 'bbknnR', raw_mat, new_mat, row_idx, col_idx)
}

UpdateIntMat <- function(raw_mat, new_mat, row_idx, col_idx) {
    .Call('_bbknnR_UpdateIntMat', PACKAGE = 'bbknnR', raw_mat, new_mat, row_idx, col_idx)
}

GetRawIndex <- function(idx_mat, raw_idx) {
    .Call('_bbknnR_GetRawIndex', PACKAGE = 'bbknnR', idx_mat, raw_idx)
}

GetSparseDist <- function(knn_index, knn_dist, n_obs, n_neighbors) {
    .Call('_bbknnR_GetSparseDist', PACKAGE = 'bbknnR', knn_index, knn_dist, n_obs, n_neighbors)
}

Trimming <- function(x, row_idx, p, trim) {
    invisible(.Call('_bbknnR_Trimming', PACKAGE = 'bbknnR', x, row_idx, p, trim))
}

