# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_num_mat <- function(raw_mat, new_mat, row_idx, col_idx) {
    .Call('_bbknnR_update_num_mat', PACKAGE = 'bbknnR', raw_mat, new_mat, row_idx, col_idx)
}

update_int_mat <- function(raw_mat, new_mat, row_idx, col_idx) {
    .Call('_bbknnR_update_int_mat', PACKAGE = 'bbknnR', raw_mat, new_mat, row_idx, col_idx)
}

get_raw_indices <- function(idx_mat, raw_idx) {
    .Call('_bbknnR_get_raw_indices', PACKAGE = 'bbknnR', idx_mat, raw_idx)
}

get_sparse_dist <- function(knn_index, knn_dist, n_obs, n_neighbors) {
    .Call('_bbknnR_get_sparse_dist', PACKAGE = 'bbknnR', knn_index, knn_dist, n_obs, n_neighbors)
}

trimming_cpp <- function(x, row_idx, p, trim) {
    invisible(.Call('_bbknnR_trimming_cpp', PACKAGE = 'bbknnR', x, row_idx, p, trim))
}

