# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

correct_idx_cpp <- function(nnidx, raw_idx) {
    .Call(`_bbknnR_correct_idx_cpp`, nnidx, raw_idx)
}

trim_graph <- function(cnt, trim) {
    .Call(`_bbknnR_trim_graph`, cnt, trim)
}

